export const CartActionTypes = {
  TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
  HIDE_CART: 'HIDE_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART',
  ONCLICK_CLEAR_BUTTON: 'ONCLICK_CLEAR_BUTTON',
};
